---
title: "obmap_enrichment_effect"
author: "kanazian"
date: "January 15, 2020"
output: html_document
---

#Goal
Determine how consistent enrichment is between biological and technical replicates of mouse OBs. Determine the range of enrichment fold for all ORs.

#setup and load data
```{r setup, message=False}
library(tidyverse)
library(heatmaply)

rawdat <- read_tsv("~/Desktop/obmap_enrichmenteffect.tsv")
olfrs_all <- rawdat[str_detect(rawdat$gene_id, "Olfr"),]
olfrs_nops <- olfrs_all[-which(str_detect(olfrs_all$gene_id, "-ps")),]
ectopic <- c("Olfr287","Olfr32")
olfrs <- olfrs_nops %>% filter(!(gene_id %in% ectopic))
```

#examine biological replicates
```{r}
bioreps <- olfrs %>% select(M10ECOB:M9OBEC, m4r2synth, m4cap) %>% select(-M6nocapOB)
#pairwise spearman correlation matrix
bio_pmtx <- matrix(data=0, nrow=ncol(bioreps), ncol=ncol(bioreps))
colnames(bio_pmtx) <- colnames(bioreps)
rownames(bio_pmtx) <- colnames(bioreps)
for (i in 1:ncol(bioreps)) {
  correlation <- vector("numeric", length = ncol(bioreps))
  for (j in 1:ncol(bioreps)) {
    if (i == j) {
      bio_pmtx[i,j] <- 1
    } else {
    bio_pmtx[i,j] <- cor(bioreps[i], bioreps[j], method = "spearman")
    }
  }
}

heatmaply_cor(bio_pmtx)

ggplot(bioreps, aes(M6OB, M10ECOB)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm")
```

#examine technical replicates of capture enrichment (2 different arrays on same cDNA, same library)
```{r}
techreps <- olfrs %>% select(NC_10Ar2, NC_10Br2, NC_4Ar2, NC_4Br2, OC_10Ar2, OC_10Br2, OC_4Ar2, OC_4Br2)
#pairwise spearman correlation matrix
tech_pmtx <- matrix(data=0, nrow=ncol(techreps), ncol=ncol(techreps))
colnames(tech_pmtx) <- colnames(techreps)
rownames(tech_pmtx) <- colnames(techreps)
for (i in 1:ncol(techreps)) {
  correlation <- vector("numeric", length = ncol(techreps))
  for (j in 1:ncol(techreps)) {
    if (i == j) {
      tech_pmtx[i,j] <- 1
    } else {
    tech_pmtx[i,j] <- cor(techreps[i], techreps[j], method = "spearman")
    }
  }
}

heatmaply_cor(tech_pmtx)

ggplot(olfrs, aes(NC_4Br2, OC_4Br2)) + 
  geom_point(alpha = 0.25) + 
  geom_smooth(method = "lm")
```

#examine fold enrichment using genomic DNA controls
```{r}
b6dna <- olfrs %>% select(gene_id, b6cap100, b6nocap7, b6nocap9, m4cap, m4uncap, M6OB, M6nocapOB) %>% mutate(foldenr7 = b6cap100/(b6nocap7 + 0.1), foldenrm4 = m4cap/(m4uncap + 0.1), foldenrm6 = M6OB/(M6nocapOB + 0.1)) %>% arrange(desc(foldenrm6)) %>% mutate(order = factor(gene_id, gene_id))

ggplot(b6dna, aes(b6nocap7, b6cap100)) +
  geom_point()

ggplot(b6dna, aes(m4uncap, m4cap)) +
  geom_point()

ggplot(b6dna, aes(M6nocapOB, M6OB)) +
  geom_point()

ggplot(b6dna, aes(order, foldenrm6)) +
  geom_bar(stat="identity") +
  ggtitle("M6OB RNA fold enrichment")

ggplot(b6dna, aes(foldenrm4, foldenrm6)) + 
  geom_point() +
  geom_smooth(method = "lm")

ggplot(b6dna, aes(m4cap, M6OB)) + 
  geom_point() +
  geom_smooth(method = "lm")

ggplot(b6dna, aes(m4uncap, M6nocapOB)) + 
  geom_point() +
  geom_smooth(method = "lm")

```

